//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotDb
    {
        public string DersId { get; set; }
        public string OgrenciNo { get; set; }
        public Nullable<int> Sinav1 { get; set; }
        public Nullable<int> Sinav2 { get; set; }
        public Nullable<int> Sinav3 { get; set; }
        public Nullable<int> Sozlu1 { get; set; }
        public Nullable<int> Sozlu2 { get; set; }
        public Nullable<int> Sozlu3 { get; set; }
        public string NotId { get; set; }
        public Nullable<float> NotOrtalamasi { get; set; }
    
        public virtual OgrenciDb OgrenciDb { get; set; }
        public virtual DersDb DersDb { get; set; }
    }
}
